Program Prostopad;
uses crt;
var a,b,h,p : real;

begin
    clrscr;
    writeln ('Program liczy pole pow. caˆkowitej prostopadˆo˜cianu');
    writeln ('wprowad« dˆugo˜† podstawy tego prostopadˆo˜cianu');
    read(a);
    If a<=0 then begin writeln ('zˆa warto˜†. podaj inn¥!!!');
                       read (a);
                 end
    writeln ('wprowad« dˆugo˜† dˆugo˜† drugiego boku podstawy');

    If a<=0 then begin writeln ('zˆa warto˜†. podaj inn¥!!!');
                       read (b);
                 end

